language: java
jdk: openjdk10

os: linux

services: docker

env:
  - COVERAGE=.10

script:
  - travis encrypt DOCKER_PASSWORD="secretvalue" --ad env.global --com
  - ./gradlew clean jar

jobs:
  include:
    - stage: test
      script: ./gradlew -p ./monolithic/ui check
      script: ./gradlew -p ./monolithic/service/cart check
      script: ./gradlew -p ./monolithic/service/user check
      script: ./gradlew -p ./monolithic/repository/order check
      script: ./gradlew -p ./monolithic/repository/cart check
      script: ./gradlew -p ./monolithic/repository/product check
      script: ./gradlew -p ./monolithic/repository/user check
    - stage: before_deploy
      script: ./gradlew -p ./monolithic/repository/ui packageToContainer
      script: docker tag natgainer/monolithic-shop:latest natgainer/ContIntCourse:latest
    - stage: deploy
      script: bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin"
      script: docker push $DOCKER_LOGIN/monolithic-ship:latest
      script: echo 'WIP'
